import useSession from "../../hooks/useSession";
import Head from "next/head";

export default function Layout({ children }: { children: React.ReactNode }) {
  const { status, user } = useSession();

  if (status === 'loading') {
    return <div>Loading...</div>;
  }
  else if (status === 'authenticated' && user) {
    return (
      <>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <h1>Logged in as {user.fullname}</h1>

        <main>
          {children}
        </main>
      </>
    )
  }
  else {
    return (
      <>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <h1>Not logged in</h1>
      </>
    )
  }
}