import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Cookies from 'cookies'

const SignUp: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Sign Up</h1>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const cookies = new Cookies(ctx.req, ctx.res);
  const token = cookies.get('auth-token');
  
  if (token) {
    return {
      redirect: {
        destination: '/dashboard',
        statusCode: 302
      }
    };
  }

  return { props: {} }
}

export default SignUp