import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Cookies from 'cookies'

const SignIn: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Sign In</h1>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {

  const { req, res } = context;

  const cookies = new Cookies(req, res);
  const token = cookies.get('auth-token');

  if (token) {
    context.res.writeHead(302, {
      Location: '/'
    });
    res.end();
  }

  return {
    props: {}
  }
}

export default SignIn
