import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import { InstantSearch } from 'react-instantsearch-hooks-web'
import searchClient from '../components/search/client'

const Search: NextPage = () => {
  const [isLoading, setLoading] = useState(false);

  return (
    <>
      <Head>
        <title>Search | Owl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* @ts-ignore */}
      <InstantSearch searchClient={searchClient} indexName="users" stalledSearchDelay={0}>
      </InstantSearch>
    </>
  )
}

export default Search
