import Head from 'next/head'
import Layout from '../components/layout'
import SearchConsole from '../components/search/console'
import { NextPageWithLayout } from '../typescript/nextpage'

const Search: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Search | Owl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchConsole />
    </>
  )
}

// return the Search page wrapped in the Layout component
Search.getLayout = function getLayout(page: React.ReactElement) {
  return <Layout>{page}</Layout>;
}

export default Search
